# Generated by Django 3.1.6 on 2021-02-05 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210205_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects', verbose_name='Fondo'),
            preserve_default=False,
        ),
    ]
